[#ftl]
[@b.head/]
[#if sessions ?? && sessions?size>0]
[#if volunteers?? && volunteers?size>0]
  [@b.toolbar title="已报名单位信息"/]
  [@b.grid items=volunteers?sort_by("indexno") var="volunteer" sortable="false"]
    [@b.row]
      [@b.col width="5%" property="indexno" title="志愿顺序"/]
      [@b.col width="15%" property="option.corporation.name" title="单位名称"/]
	    [@b.col width="30%" property="option.benefits" title="要求"/]
	    [@b.col width="30%" property="option.request" title="福利条件"/]
	    [@b.col width="5%" property="option.capacity" title="人数上限"/]
	    [@b.col width="5%" property="option.actual" title="实际人数"/]
      [@b.col width="10%" title="操作"]
        [@b.a href="!unChoose?volunteer.id=${volunteer.id}&session.id=${session.id }"]取消报名[/@]
        [#if volunteers?size == 2]
          [@b.a href="!changeNo?session.id=${session.id }"]更改顺序[/@]
        [/#if]
      [/@]
    [/@]
  [/@]
[/#if]

<div class="container">法律助理报名时间为${session.beginAt}到${session.endAt }.[@b.a class="btn btn-default" href="!options" role="button"]报名[/@]</div>
[#else]法律助理报名还未开始
[/#if]
[@b.foot/]
