[#ftl]
[@b.head/]
[@b.toolbar title="新增/修改评审专家"]bar.addBack();[/@]
[@b.tabs]
  [@b.form theme="list" action=b.rest.save(laDepart)]
    [@b.textfield name="laDepart.name" label="单位名称" value="${laDepart.name!}" required="true" maxlength="80" style="width:200px;"/]
    [@b.radios label="开关状态" name="laDepart.opened" value=laDepart.opened items="1:是,0:fou" required="true"/]
    [@b.textarea name="laDepart.request" label="要求" value="${laDepart.request!}" maxlength="2000" style="width:200px;"/]
    [@b.textarea name="laDepart.benefits" label="福利条件" value="${laDepart.benefits!}" maxlength="2000" style="width:200px;"/]
    [@b.textfield name="laDepart.capacity" label="人数上限" value="${laDepart.capacity!}" required="true" maxlength="80" style="width:200px;"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
