[#ftl]
[@b.head/]
[@b.toolbar title="新增/修改项目单位要求"]bar.addBack();[/@]
  [@b.form theme="list" action=b.rest.save(laOption)]
    [@b.select label="学年学期" name="laOption.semester.id" items=semesters?sort_by("code")?reverse required="true" value=currentSemester option=r"${item.schoolYear}学年${item.name}学期" style="width:200px"/]
    [@b.select label="单位" name="laOption.corporation.id" items=corporations required="true"  style="width:200px;" value=laOption.corporation! /]
    [@b.textarea name="laOption.requirement" label="要求" value="${laOption.requirement!}" maxlength="2000"  cols="100" rows="10"/]
    [@b.textarea name="laOption.remark" label="备注" value="${laOption.remark!}" maxlength="2000"  cols="100" rows="10"/]
    [@b.textfield name="laOption.capacity" label="人数上限" value="${laOption.capacity}" required="true" style="width:50px;"/]
    [@b.textfield name="laOption.enrolled" label="拟录取" value="${laOption.enrolled}" required="true" style="width:50px;"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
