[#ftl]
[@b.head/]
[@b.toolbar title="新增/修改单位"]bar.addBack();[/@]
[@b.tabs]
  [@b.form theme="list" action=b.rest.save(corporation)]
    [@b.textfield name="corporation.name" label="单位名称" value="${corporation.name!}" required="true" maxlength="80" style="width:200px;"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
