[#ftl]
[@b.head/]
[@b.toolbar title="新增/修改企业"]bar.addBack();[/@]
[@b.tabs]
  [@b.form theme="list" action=b.rest.save(corporation)]
    [@b.textfield name="corporation.name" label="单位名称" value="${corporation.name!}" required="true" maxlength="80" style="width:200px;"/]
    [@b.textarea name="corporation.request" label="要求" value="${corporation.request!}" maxlength="2000" cols="150" rows="20"/]
    [@b.textarea name="corporation.benefits" label="福利条件" value="${corporation.benefits!}" maxlength="2000" cols="150" rows="20"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
