[#ftl]
[@b.head/]
[@b.grid items=volunteers var="volunteer"]
  [@b.row]
    [@b.boxcol /]
      [@b.col property="indexno" title="志愿顺序" width="5%"/]
      [@b.col property="std.user.code" title="学号" width="9%"/]
      [@b.col property="std.user.name" title="姓名" width="8%"/]
      [@b.col property="std.state.grade" title="年级" width="8%"/]
      [@b.col property="std.state.department.name" title="管理院系" width="20%"/]
      [@b.col property="std.state.major.name" title="专业" width="20%"]${(audience.std.state.major.name)!} ${(audience.std.state.direction.name)!}[/@]
      [@b.col property="std.state.squad.name"  title="班级" width="20%"/]
      [@b.col title="是否可调剂" width="10%"]${volunteer.adjust?string("是","否") }[/@]
  [/@]
[/@]

[@b.foot/]
