[@b.form action=b.rest.save(laTaker) theme="list"]
  [@b.field label="学号"]${laTaker.volunteer.std.code}[/@]
  [@b.field label="姓名"]${laTaker.volunteer.std.name}[/@]
  [@b.field label="院系"]${(laTaker.volunteer.std.state.department.name)!'--'}[/@]
  [@b.field label="绩点"]${(laTaker.volunteer.gpa)!'--'}[/@]
  [@b.field label="联系方式"]${laTaker.volunteer.mobile}[/@]
  [@b.field label="报名单位"]${laTaker.option.corporation.name}[/@]
  [@b.radios label="是否录取" name="enrolled" items={'1':'是','0':'否'} value=laTaker.enrolled  required="true"/]
  [@b.formfoot]
    [@b.submit value="提交"/]
  [/@]
[/@]
